import { test, expect } from '@playwright/test';
import { gotoTab } from './utils';

test.describe('Dynamic ID Handling', () => {
  test('selects "Beta" by visible name regardless of regenerated ids', async ({ page }) => {
    await page.goto('/');
    await gotoTab(page, 'Flaky Selectors');

    await page.getByRole('button', { name: 'Regenerate All IDs' }).click();

    // Select strictly by visible text/accessible name -- never by #id,
    // since ids are intentionally regenerated by the app. Prefer a semantic
    // role (button/option) that contains the "Beta" text.
    const betaItem = page
      .getByRole('button', { name: 'Beta' })
      .or(page.getByRole('option', { name: 'Beta' }))
      .or(page.getByText('Beta', { exact: true }))
      .first();
    await betaItem.click();

    // Verify selection via an accessible/visual signal rather than an id:
    // prefer aria-selected/aria-pressed if the app exposes it, otherwise
    // fall back to a "selected" class or nearby confirmation text.
    const ariaState = await betaItem.getAttribute('aria-selected');
    if (ariaState !== null) {
      expect(ariaState).toBe('true');
    } else {
      const classes = (await betaItem.getAttribute('class')) ?? '';
      const isSelectedByClass = /selected|active/i.test(classes);
      const hasSelectedText = await page.getByText(/beta.*selected|selected.*beta/i).count();
      expect(isSelectedByClass || hasSelectedText > 0).toBeTruthy();
    }

    // Re-run the regenerate step to prove the selection logic is id-agnostic.
    await page.getByRole('button', { name: 'Regenerate All IDs' }).click();
    await expect(page.getByText('Beta', { exact: true })).toBeVisible();
  });
});
